import type { Entity, ResourceType, WorkspaceData } from './types';
const item = (type: ResourceType, n: number, data: Omit<Entity, 'id' | 'type'>): Entity => ({ ...data, name: String(data.name), id: `demo-${type}-${n}`, type });
const sourceRows = [
  ['Facebook', 'Publications, commentaires, mentions et pages associées.', 'social', 12450, 12, 'facebook'],
  ['Instagram', 'Photos, stories, commentaires et hashtags.', 'social', 8320, 8, 'instagram'],
  ['X (Twitter)', 'Tweets, réponses et mentions.', 'social', 15870, 15, 'x'],
  ['YouTube', 'Vidéos, commentaires et mentions.', 'social', 6430, 11, 'youtube'],
  ['LinkedIn', 'Profils, publications et interactions.', 'social', 3210, 7, 'linkedin'],
  ['TikTok', 'Vidéos, commentaires et tendances.', 'social', 11360, 20, 'tiktok'],
  ['Google News', 'Articles de presse et actualités.', 'media', 4870, 9, 'google'],
  ['Blogs & Sites web', 'Articles de blogs, forums et sites spécialisés.', 'web', 2340, 6, 'web'],
  ['Forums', 'Discussions sur des forums et communautés.', 'other', 1920, 4, 'forum'],
  ['Presse en ligne', 'Sites d’actualité et médias en ligne.', 'media', 5670, 10, 'presse'],
  ['WhatsApp', 'Messages publics et groupes ouverts.', 'social', 980, 3, 'whatsapp'],
  ['Autres sources', 'APIs, bases de données et sources personnalisées.', 'other', 1150, 5, 'other'],
  ['Google Search', 'Résultats de recherche et pages indexées.', 'search', 2680, 8, 'google'],
  ['Bing', 'Résultats du moteur de recherche Bing.', 'search', 810, 4, 'web'],
  ['Reddit', 'Communautés et discussions publiques.', 'social', 620, 9, 'forum'],
  ['Telegram', 'Canaux et groupes publics.', 'social', 750, 5, 'web'],
  ['Africa 24', 'Actualités et informations panafricaines.', 'media', 420, 6, 'presse'],
  ['Cameroon24', 'Actualité nationale et régionale.', 'media', 880, 12, 'presse'],
  ['Le Monde', 'Presse internationale francophone.', 'media', 530, 4, 'presse'],
  ['Medium', 'Articles et publications d’experts.', 'web', 260, 3, 'web'],
];
const mentions: Partial<Entity>[] = [
  { name: 'Très belle initiative de M. Kenne pour la formation des jeunes !', platform: 'tiktok', author: '@vision_africa', sentiment: 'positive', score: 94, time: 'Il y a 12 min', views: '12,4 K', category: 'Formation / Éducation' },
  { name: 'Une personne engagée et inspirante ! Bravo pour cette intervention sur l’innovation technologique.', platform: 'facebook', author: 'Marie D.', sentiment: 'positive', score: 92, time: 'Il y a 28 min', views: '842', category: 'Innovation technologique' },
  { name: 'Interview exclusive avec Arnaud Kenne sur l’innovation en Afrique.', platform: 'presse', author: 'Cameroon24', sentiment: 'neutral', score: 68, time: 'Il y a 1 h', views: '23', category: 'Innovation technologique' },
  { name: 'Pas très convaincu par certains projets annoncés. Nous attendons des résultats concrets.', platform: 'x', author: '@critic_db', sentiment: 'negative', score: 35, time: 'Il y a 2 h', views: '1,3 K', category: 'Business / Entrepreneuriat' },
  { name: 'Présentation complète des solutions Ghostroar. Une belle avancée pour le digital !', platform: 'youtube', author: 'Tech Africa', sentiment: 'positive', score: 85, time: 'Il y a 3 h', views: '54,7 K', category: 'Innovation technologique' },
  { name: 'Un expert passionné et un vrai leader dans son domaine.', platform: 'linkedin', author: 'Cameroon Business', sentiment: 'positive', score: 90, time: 'Il y a 2 h', views: '4,2 K', category: 'Business / Entrepreneuriat' },
  { name: 'Analyse complète de ses projets et de ses réalisations.', platform: 'web', author: 'TechNews-CM', sentiment: 'negative', score: 45, time: 'Il y a 4 h', views: '1,1 K', category: 'Cybersécurité' },
  { name: 'La transformation digitale de l’Afrique passe par la formation.', platform: 'linkedin', author: 'Innovation TV', sentiment: 'positive', score: 91, time: 'Il y a 5 h', views: '2,6 K', category: 'Formation / Éducation' },
  { name: 'Un nouveau programme de cybersécurité présenté à Yaoundé.', platform: 'presse', author: 'Le Quotidien', sentiment: 'neutral', score: 64, time: 'Il y a 6 h', views: '790', category: 'Cybersécurité' },
  { name: 'Merci pour cette masterclass enrichissante et accessible.', platform: 'instagram', author: 'Sarah M.', sentiment: 'positive', score: 96, time: 'Il y a 7 h', views: '5,8 K', category: 'Formation / Éducation' },
  { name: 'Des solutions concrètes pour les entrepreneurs camerounais.', platform: 'facebook', author: 'Digital Cameroon', sentiment: 'positive', score: 87, time: 'Il y a 8 h', views: '3,4 K', category: 'Business / Entrepreneuriat' },
  { name: 'Conférence sur la protection des données personnelles ce vendredi.', platform: 'x', author: '@tech_watch', sentiment: 'neutral', score: 61, time: 'Il y a 9 h', views: '940', category: 'Cybersécurité' },
  { name: 'La plateforme pourrait être plus accessible aux petites structures.', platform: 'forum', author: 'Jean P.', sentiment: 'negative', score: 42, time: 'Il y a 10 h', views: '560', category: 'Autres' },
  { name: 'Fier de voir cette innovation camerounaise rayonner !', platform: 'tiktok', author: '@africa_futur', sentiment: 'positive', score: 98, time: 'Il y a 11 h', views: '18,2 K', category: 'Innovation technologique' },
  { name: 'L’équipe Ghostroar annonce de nouvelles fonctionnalités de veille.', platform: 'web', author: 'Tech & Co', sentiment: 'neutral', score: 70, time: 'Hier', views: '1,8 K', category: 'Innovation technologique' },
];
export const demoData: WorkspaceData = {
  sources: sourceRows.map((r, i) => item('sources', i + 1, { name: String(r[0]), description: String(r[1]), category: String(r[2]), count: Number(r[3]), growth: Number(r[4]), platform: String(r[5]), status: i === 10 ? 'partial' : i > 17 ? 'inactive' : 'connected', active: i <= 17, url: `https://${({ facebook:'facebook.com', instagram:'instagram.com', youtube:'youtube.com', linkedin:'linkedin.com', x:'x.com', tiktok:'tiktok.com' } as Record<string, string>)[String(r[5])] || 'example.com'}` })),
  mentions: mentions.map((m, i) => item('mentions', i + 1, { ...m, name: m.name!, date: '2026-09-12', url: 'https://www.linkedin.com', status: 'new' })),
  alerts: [
    { name: 'Mention critique sur LinkedIn', description: 'Publication virale remettant en cause votre intégrité professionnelle.', severity: 'critical', status: 'unread', platform: 'linkedin', time: 'Il y a 15 min', author: 'Jean Dupont' },
    { name: 'Pic de mentions négatives sur X', description: 'Augmentation soudaine des mentions négatives en 1 h.', severity: 'high', status: 'in_progress', platform: 'x', time: 'Il y a 1 h' },
    { name: 'Article de presse défavorable', description: 'Article publié sur un site média à forte audience.', severity: 'medium', status: 'resolved', platform: 'presse', time: 'Il y a 3 h' },
    { name: 'Usurpation d’identité détectée', description: 'Profil suspect utilisant votre nom et votre image.', severity: 'critical', status: 'unread', platform: 'web', time: 'Il y a 5 h' },
    { name: 'Alerte réputation : baisse de sentiment', description: 'Le sentiment global a chuté de 18 % en 24 h.', severity: 'high', status: 'in_progress', platform: 'other', time: 'Il y a 6 h' },
    { name: 'Publication virale détectée', description: 'TikTok · 72 430 vues (+8 200 en 15 min)', severity: 'critical', status: 'unread', platform: 'tiktok', time: 'Il y a 12 min' },
    { name: 'Mention positive importante', description: 'Facebook · Interview en ligne', severity: 'low', status: 'resolved', platform: 'facebook', time: 'Il y a 1 h' },
    { name: 'Hausse des mentions', description: '+45 % sur Instagram', severity: 'info', status: 'unread', platform: 'instagram', time: 'Il y a 3 h' },
  ].map((d, i) => item('alerts', i + 1, d)),
  publications: [
    { name: 'Stratégies de réputation à l’ère de l’IA', description: 'Décryptage des meilleures pratiques pour protéger et valoriser votre image.', platform: 'linkedin', status: 'published', views: '12,4 K', likes: 512, comments: 48, score: 92, date: '2026-09-12T09:30', image: 'speaker' },
    { name: 'Veille e-réputation : tendances 2026', description: 'Les grandes tendances à suivre pour anticiper les risques et opportunités.', platform: 'x', status: 'published', views: '8,7 K', likes: 341, comments: 27, score: 78, date: '2026-09-10T16:15', image: 'x' },
    { name: 'L’importance de l’authenticité', description: 'Pourquoi l’authenticité reste votre meilleur atout réputationnel.', platform: 'instagram', status: 'scheduled', views: '—', likes: 0, comments: 0, score: 0, date: '2026-09-17T10:00', image: 'notebook' },
    { name: 'Podcast : Crise réputationnelle, et après ?', description: 'Retour d’expérience et conseils d’experts pour rebondir.', platform: 'youtube', status: 'published', views: '15,6 K', likes: 782, comments: 63, score: 88, date: '2026-09-08T14:00', image: 'podcast' },
    { name: 'Cybersécurité : les réflexes essentiels', description: 'Cinq conseils pour protéger votre identité numérique au quotidien.', platform: 'linkedin', status: 'draft', views: '—', likes: 0, comments: 0, score: 0, date: '2026-09-20T10:00', image: 'speaker' },
  ].map((d, i) => item('publications', i + 1, d)),
  contacts: [
    { name: 'Jean Dupont', company: 'Le Quotidien', role: 'Journaliste – Politique & Société', category: 'Presse', score: 85, sentiment: 'positive', platform: 'person', email: 'jean.dupont@example.com' },
    { name: 'Marie Lemoine', company: 'France 24', role: 'Grand reporter – International', category: 'TV', score: 78, sentiment: 'neutral', platform: 'tv', email: 'marie.lemoine@example.com' },
    { name: 'Thomas Rivière', company: 'Le Monde', role: 'Journaliste – Tech & Numérique', category: 'Presse', score: 72, sentiment: 'positive', platform: 'lemonde', email: 'thomas.riviere@example.com' },
    { name: 'Sophie Martin', company: 'Europe 1', role: 'Productrice – Matinale Info', category: 'Radio', score: 81, sentiment: 'neutral', platform: 'radio', email: 'sophie.martin@example.com' },
    { name: 'Alexandre Bernard', company: 'Tech & Co', role: 'Rédacteur en chef – Innovation', category: 'Web', score: 68, sentiment: 'negative', platform: 'tech', email: 'alexandre.bernard@example.com' },
    { name: 'Cédric Lefèvre', company: 'BFM Business', role: 'Journaliste – Économie', category: 'TV', score: 82, sentiment: 'positive', platform: 'bfm', email: 'cedric.lefevre@example.com' },
    { name: 'Aminata Diallo', company: 'Africa 24', role: 'Journaliste – Innovation', category: 'TV', score: 90, sentiment: 'positive', platform: 'tv', email: 'aminata.diallo@example.com' },
    { name: 'Paul Mbarga', company: 'Cameroon24', role: 'Rédacteur – Actualités', category: 'Web', score: 75, sentiment: 'neutral', platform: 'web', email: 'paul.mbarga@example.com' },
  ].map((d, i) => item('contacts', i + 1, { ...d, country: 'France', status: 'active', notes: '', date: '2026-09-12' })),
  reports: [
    { name: 'Rapport mensuel – Août 2026', category: 'Mensuel', date: '2026-09-12', description: 'Bilan de votre réputation : score 78/100, 2 487 mentions, 70,1 % de sentiment positif.' },
    { name: 'Rapport d’analyse – 30 derniers jours', category: 'Analyse', date: '2026-09-10', description: 'Analyse des tendances et des conversations sur vos 18 sources actives.' },
    { name: 'Bilan réputation – T2 2026', category: 'Trimestriel', date: '2026-09-08', description: 'Évolution trimestrielle de votre visibilité, crédibilité et autorité.' },
    { name: 'Rapport de crise – Alertes', category: 'Crise', date: '2026-09-05', description: 'Synthèse des alertes traitées et des plans de réponse.' },
  ].map((d, i) => item('reports', i + 1, { ...d, status: 'ready' })),
  rules: [
    { name: 'Mentions critiques', description: 'Sévérité : Critique', severity: 'critical', category: 'sentiment', active: true },
    { name: 'Pic de mentions', description: 'Seuil : +50 % en 1 h', severity: 'high', category: 'volume', active: true },
    { name: 'Usurpation d’identité', description: 'Surveillance continue', severity: 'critical', category: 'identity', active: true },
    { name: 'Sentiment négatif', description: 'Seuil : -15 % en 24 h', severity: 'medium', category: 'sentiment', active: true },
  ].map((d, i) => item('rules', i + 1, d)),
  crises: [item('crises', 1, { name: 'Pic de mentions négatives – Usurpation d’identité', description: 'Un compte non officiel utilise votre nom et votre image. Le plan de réponse est en cours.', status: 'active', severity: 'critical', progress: 62, assignee: 'Arnaud Kenne, Camille Dubois, Julien Moreau, Sophie Leroy', date: '2026-09-12T12:47', notes: 'Plan Critique actif. Vérification du profil, signalement et préparation d’une communication officielle.' })],
  profile: [item('profile', 1, { name: 'Arnaud TIOTSOP KENNE', description: 'Entrepreneur, expert en technologies de l’information et de l’innovation, spécialisé dans le développement de solutions digitales, la cybersécurité et la formation. Directeur de Ghostroar Digital et Fondateur de l’IFPTII (Institut de Formation Professionnelle en Technologie de l’Information et de l’Innovation). Engagé pour le développement du numérique en Afrique, notamment au Cameroun.', email: 'arnaud.kenne@ghostroar.com', phone: '+237 651 395 504', city: 'Yaoundé', country: 'Cameroun', url: 'https://www.ghostroar.com', role: 'Entrepreneur / Formateur / Expert IT', company: 'Ghostroar Digital', domain: 'Informatique, Digital, Cybersécurité', languages: 'Français, Anglais', status: 'active', active: true })],
  appointments: [
    item('appointments', 1, { name: 'Interview – France 24', author: 'Marie Lemoine', company: 'France 24', date: '2026-09-18T10:00', email: 'marie.lemoine@example.com', status: 'scheduled', description: 'Entretien sur l’innovation et la transformation numérique en Afrique.' }),
    item('appointments', 2, { name: 'Point presse – Tech & Co', author: 'Alexandre Bernard', company: 'Tech & Co', date: '2026-09-20T14:30', email: 'alexandre.bernard@example.com', status: 'scheduled', description: 'Présentation des nouvelles solutions de veille.' }),
    item('appointments', 3, { name: 'Interview radio – Europe 1', author: 'Sophie Martin', company: 'Europe 1', date: '2026-09-23T09:15', email: 'sophie.martin@example.com', status: 'scheduled', description: 'Échange autour de la protection de l’identité numérique.' }),
  ],
  campaigns: [
    item('campaigns', 1, { name: 'Innovation africaine 2026', description: 'Faire connaître nos initiatives pour l’innovation et la formation en Afrique.', status: 'active', date: '2026-09-01', assignee: 'Camille Dubois', count: 12 }),
    item('campaigns', 2, { name: 'Protection de l’identité numérique', description: 'Sensibilisation à la protection de la réputation et des données personnelles.', status: 'active', date: '2026-09-06', assignee: 'Arnaud Kenne', count: 8 }),
    item('campaigns', 3, { name: 'Former les talents de demain', description: 'Valoriser les formations et les témoignages de jeunes talents.', status: 'active', date: '2026-09-10', assignee: 'Julien Moreau', count: 6 }),
  ],
  settings: [item('settings', 1, { name: 'Préférences du compte', emailAlerts: true, pushAlerts: true, digest: false, languages: 'Français', status: 'active' })],
};
export const platformNames: Record<string, string> = { facebook: 'Facebook', instagram: 'Instagram', x: 'X (Twitter)', youtube: 'YouTube', linkedin: 'LinkedIn', tiktok: 'TikTok', presse: 'Média', web: 'Blog Web', google: 'Google News', forum: 'Forums', whatsapp: 'WhatsApp', other: 'Analyse IA' };
