'use client';
import { useEffect, useState } from 'react';
import { demoData, platformNames } from '@/lib/demo-data';
import { useWorkspace } from '../workspace-context';
import { PageHeading } from '../app-shell';
import { Avatar, Badge, Button, EmptyState, Icon, IconButton, Panel, Pagination, PlatformIcon, Select, TextLink, Toggle } from '../ui';
import { LineChart } from '../charts';
import { StatCard } from './dashboard';

export function AlertsView() {
  const { data, edit, detail, save, notify, exportData } = useWorkspace();
  const [severity,setSeverity]=useState('all'),[status,setStatus]=useState('all'),[source,setSource]=useState('all'),[period,setPeriod]=useState('all'),[query,setQuery]=useState(''),[page,setPage]=useState(1),[manageRules,setManageRules]=useState(false);
  const filtered=data.alerts.filter((a,i)=>(severity==='all'||a.severity===severity)&&(status==='all'?a.status!=='archived':a.status===status)&&(source==='all'||a.platform===source)&&(period==='all'||i<5)&&`${a.name} ${a.description}`.toLowerCase().includes(query.toLowerCase()));
  const actualPage=Math.min(page,Math.max(1,Math.ceil(filtered.length/5)));
  const critical=2+data.alerts.filter(a=>a.severity==='critical'&&a.status!=='resolved').length-demoData.alerts.filter(a=>a.severity==='critical'&&a.status!=='resolved').length;
  const unread=5+data.alerts.filter(a=>a.status==='unread').length-demoData.alerts.filter(a=>a.status==='unread').length;
  const resolved=47+data.alerts.filter(a=>a.status==='resolved').length-demoData.alerts.filter(a=>a.status==='resolved').length;
  async function update(id:string,next:string){const result=await save('alerts',{status:next},id);if(result)notify(next==='resolved'?'L’alerte est résolue.':'L’alerte a été archivée.');}
  return <div className="section-page alerts-page"><div className="classic-two-column"><div className="classic-main"><PageHeading title="Gestion des alertes" active subtitle="◷  Dernière mise à jour : 12 sept. 2026, 14:32" /><div className="four-metrics"><StatCard title="Alertes critiques" icon="trend" tone="red" value={Math.max(0,critical)} /><StatCard title="Non lues" icon="mail" tone="yellow" value={Math.max(0,unread)} /><StatCard title="En cours de traitement" icon="clock" tone="blue" value={data.alerts.filter(a=>a.status==='in_progress').length+6} /><StatCard title="Résolues ce mois" icon="success" value={resolved} /></div>
    <div className="alert-filters"><Select value={severity} aria-label="Sévérité" onChange={e=>{setSeverity(e.target.value);setPage(1);}}><option value="all">Sévérité</option><option value="critical">Critique</option><option value="high">Élevée</option><option value="medium">Moyenne</option><option value="low">Basse</option><option value="info">Information</option></Select><Select value={status} aria-label="Type d’alerte" onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="all">Type d’alerte</option><option value="unread">Non lues</option><option value="in_progress">En cours</option><option value="resolved">Résolues</option><option value="archived">Archivées</option></Select><Select value={source} aria-label="Source de l’alerte" onChange={e=>{setSource(e.target.value);setPage(1);}}><option value="all">Source</option>{Object.entries(platformNames).map(([key,name])=><option key={key} value={key}>{name}</option>)}</Select><Select value={period} aria-label="Période des alertes" onChange={e=>{setPeriod(e.target.value);setPage(1);}}><option value="all">Période</option><option value="recent">Plus récentes</option></Select><label className="table-search"><Icon name="search" size={17} /><input placeholder="Rechercher dans les alertes..." aria-label="Rechercher dans les alertes" value={query} onChange={e=>{setQuery(e.target.value);setPage(1);}} /></label></div>
    <div className="alert-list-panel"><div className="alert-cards">{filtered.slice((actualPage-1)*5,actualPage*5).map(a=><article className={`alert-card alert-${a.severity}`} key={a.id}><span className="alert-card-icon"><Icon name={a.severity==='critical'?'alert':a.severity==='high'?'fire':a.severity==='medium'?'star':'bell'} size={29} /></span><div className="alert-card-content"><div className="alert-card-title"><h3>{a.name}</h3><Badge status={a.status} subtle /></div><p>{a.description}</p><div className="alert-bottom"><span className="alert-source"><PlatformIcon platform={a.platform} size="small" />{platformNames[a.platform||'web']}<span>{a.time}</span></span><div className="alert-buttons"><Button icon="down" className="button-sm" onClick={()=>detail(a)}>Voir</Button><Button className="button-sm" onClick={()=>edit('alerts',a,{status:'in_progress'})}>{a.assignee?'Réassigner':'Assigner'}</Button><Button className="button-sm" onClick={()=>void update(a.id,a.status==='resolved'?'unread':'resolved')}>{a.status==='resolved'?'Rouvrir':'Résoudre'}</Button><Button className="button-sm" onClick={()=>void update(a.id,a.status==='archived'?'unread':'archived')}>{a.status==='archived'?'Restaurer':'Archiver'}</Button></div></div></div></article>)}</div>{!filtered.length&&<EmptyState title="Tout est sous contrôle" message="Aucune alerte ne correspond à vos filtres." icon="shield" action={<Button onClick={()=>{setSeverity('all');setStatus('all');setSource('all');setQuery('');setPeriod('all');}}>Réinitialiser les filtres</Button>} />}<Pagination page={actualPage} total={filtered.length} perPage={5} onChange={setPage} /></div></div>
    <aside className="classic-aside"><Panel title="Actions rapides" icon="bolt" className="quick-action-panel"><Button icon="plus" onClick={()=>edit('alerts')}>Créer une alerte</Button><Button icon="settings" onClick={()=>setManageRules(!manageRules)}>{manageRules?'Terminer la configuration':'Configurer les règles'}</Button><Button icon="download" onClick={()=>void exportData('alerts')}>Exporter</Button></Panel><Button variant="primary" icon="plus" className="create-rule-button" onClick={()=>edit('rules')}>Créer une règle</Button><Panel title="Règles actives" icon="shield" className="active-rules">{data.rules.map(rule=><div className="rule-row" key={rule.id}><i className={`dot ${rule.active?'green':'muted'}`} /><button onClick={()=>edit('rules',rule)}><strong>{rule.name}</strong><small>{rule.description}</small></button>{manageRules?<Toggle checked={Boolean(rule.active)} label={`Activer la règle ${rule.name}`} onChange={()=>void save('rules',{active:!rule.active},rule.id)} />:<button className={rule.active?'text-green':'text-muted'} onClick={()=>void save('rules',{active:!rule.active},rule.id)}>{rule.active?'Active':'Inactive'}</button>}</div>)}<TextLink onClick={()=>setManageRules(!manageRules)}>{manageRules?'Terminer la configuration':'Voir toutes les règles'}</TextLink></Panel><Panel title="Dernières résolutions" icon="success" className="recent-resolutions">{data.alerts.filter(a=>a.status==='resolved').slice(0,3).map(a=><button key={a.id} onClick={()=>detail(a)}><span className="resolution-check"><Icon name="check" size={15} /></span><span><strong>{a.name}</strong><small>Marqué comme résolu par {a.assignee||'vous'}</small><small>{a.time}</small></span></button>)}{!data.alerts.some(a=>a.status==='resolved')&&<p className="text-muted">Aucune alerte résolue pour le moment.</p>}<TextLink onClick={()=>{setStatus('resolved');setPage(1);}}>Voir tout le journal</TextLink></Panel></aside></div></div>;
}

const team=[['Arnaud Kenne','Administrateur'],['Camille Dubois','Responsable Communication'],['Julien Moreau','Analyste Senior'],['Sophie Leroy','Conseiller Juridique'],['Thomas Bernard','Expert Médias'],['Élodie Martin','Community Manager']];
export function CrisisView() {
  const { data, edit, detail, save, notify, openModal, navigate, refresh, syncing }=useWorkspace();
  const [live,setLive]=useState(true),[offset,setOffset]=useState(0);
  useEffect(()=>{if(!live)return;const timer=setInterval(()=>setOffset(v=>(v+1)%5),12000);return()=>clearInterval(timer);},[live]);
  const crisis=data.crises[0];
  const active=crisis&&crisis.status!=='closed';
  const feed=[...data.mentions.filter(m=>m.sentiment==='negative'),...data.mentions.filter(m=>m.sentiment==='neutral'),...data.mentions.filter(m=>m.sentiment==='positive')].slice(0,8);
  async function planAction(action:string){if(!crisis){edit('crises');return;}const changes=action==='close'?{status:active?'closed':'active',progress:active?100:62}:action==='escalate'?{severity:'critical',status:'active',notes:`${crisis.notes||''}\nEscalade déclenchée le ${new Date().toLocaleString('fr-FR')}. Équipe juridique mobilisée.`}:{status:'active',progress:Math.min(95,(crisis.progress||0)+10),notes:`${crisis.notes||''}\nPlan de réponse activé. Vérification des comptes et préparation du communiqué.`};const result=await save('crises',changes,crisis.id);if(result)notify(action==='close'?(active?'La crise a été clôturée. La surveillance reste active.':'La War Room est réactivée.'):action==='escalate'?'La crise a été escaladée à l’équipe juridique.':'Le plan de réponse est activé.');}
  return <div className="section-page crisis-page"><div className="crisis-columns"><div className="crisis-main"><div className="breadcrumb"><button onClick={()=>navigate('dashboard')}>Accueil</button><Icon name="right" size={12} /><span>Gestion de crise</span></div><div className="war-room-heading"><h1>War Room – Gestion de crise</h1><Badge status={active?'critical':'resolved'} subtle>{active?'CRISE ACTIVE':'CRISE MAÎTRISÉE'}</Badge><span>Dernière mise à jour : 12 sept. 2026, 14:32:47</span><IconButton name="refresh" label="Actualiser la War Room" className={syncing?'spin':''} onClick={()=>void refresh()} /></div><div className="four-metrics"><StatCard title="Crises actives" value={active?1:0} icon="users" tone="red" subtitle={active?'En cours':'Aucune crise active'} /><StatCard title="Impact réputation" value={active?'-12,4%':'0%'} icon="neutral" tone="yellow" subtitle="Évolution (24 h)" /><StatCard title="Mentions critiques" value={active?47:0} icon="user" tone="red" subtitle="(2 dernières heures)" /><StatCard title="Équipe en ligne" value="6/8" icon="user" subtitle="Membres connectés" /></div>
    <div className="war-room-content"><div className="war-room-left"><Panel title={<><i className={`dot ${active?'red':'green'}`} />{active?'CRISE ACTIVE':'SITUATION MAÎTRISÉE'}</>} className="active-crisis"><h2>{crisis?.name||'Aucune crise en cours'}</h2><div className="crisis-meta"><Badge status={active?'critical':'resolved'} subtle>{active?'CRITIQUE':'CLÔTURÉE'}</Badge><span>Débutée le : 12 sept. 2026, 12:47</span><span>Statut : {active?'En cours':'Clôturée'}</span></div><div className="crisis-progress-label"><span>Plan de réponse {active?'en cours':'terminé'}</span><strong>{crisis?.progress||0}%</strong></div><button className="progress-track crisis-progress" onClick={()=>crisis?edit('crises',crisis):edit('crises')} title="Gérer le plan de réponse"><i style={{width:`${crisis?.progress||0}%`,background:active?'var(--red)':'var(--green)'}} /></button><div className="assigned-team"><h3>Équipe assignée</h3><button onClick={()=>openModal({kind:'team'})}>{team.slice(0,4).map(([name,role],i)=><span key={name}>{i===0?<Avatar size="small" />:<span className={`initial-avatar color-${i}`}>{name.split(' ').map(n=>n[0]).join('')}</span>}<span><strong>{name}</strong><small>{role}</small></span></span>)}<b>+2</b></button></div></Panel><Panel title={<><i className="dot green" />TIMELINE EN DIRECT</>} action={<Button className="button-sm" onClick={()=>navigate('mentions')}>Tout voir</Button>} className="crisis-timeline">{[['14:32','x','Nouveau pic de mentions sur X','#Usurpation #Arnaque','negative'],['14:28','linkedin','Publication LinkedIn virale','Compte tiers – Accusations','negative'],['14:21','presse','Article de presse en ligne','Le site média publie un article','negative'],['14:15','web','Blog & forums – Discussions','Plusieurs fils de discussion actifs','neutral'],['14:07','x','Réaction d’un influenceur','25 K abonnés – Mention négative','negative'],['13:59','facebook','Mention positive détectée','Soutien spontané d’un utilisateur','positive']].map(([time,platform,title,text,sentiment],i)=><button key={time} onClick={()=>data.mentions[i]?detail(data.mentions[i]):navigate('mentions')}><time>{time}</time><i className={`timeline-point ${sentiment==='positive'?'green':''}`} /><PlatformIcon platform={platform} size="small" /><span><strong>{title}</strong><small>{text}</small></span><Badge status={sentiment} subtle>{sentiment==='positive'?'Positif':sentiment==='negative'?'Négatif':'Neutre'}</Badge></button>)}</Panel></div>
    <Panel title="MENTIONS EN TEMPS RÉEL" className="crisis-stream"><div className="stream-toggle"><span><i className={`dot ${live?'green':'muted'}`} />Défilement automatique</span><Toggle label="Défilement automatique des mentions" checked={live} onChange={()=>setLive(!live)} /></div><div className="stream-cards">{Array.from({length:Math.min(5,feed.length)},(_,i)=>feed[(i+offset)%feed.length]).map((m,i)=><button className="stream-card" key={`${m.id}-${i}`} onClick={()=>detail(m)}><PlatformIcon platform={m.platform} size="small" /><span><small>{platformNames[m.platform||'web']} · {m.author}</small><p>{m.name}</p></span><Badge status={m.sentiment} subtle>{m.sentiment==='positive'?'Positif':m.sentiment==='negative'?'Négatif':'Neutre'}</Badge></button>)}</div><TextLink onClick={()=>navigate('mentions')}>Voir toutes les mentions</TextLink></Panel></div></div>
    <aside className="crisis-aside"><Panel title="ACTIONS DE CRISE" className="crisis-actions"><Button icon="crisis" className="action-red" onClick={()=>void planAction('activate')}>Activer plan de réponse<Icon name="right" size={15} /></Button><Button icon="users" onClick={()=>openModal({kind:'communication',title:'Communication de crise'})}>Communiquer<Icon name="right" size={15} /></Button><Button icon="alert" className="action-yellow" onClick={()=>void planAction('escalate')}>Escalader<Icon name="right" size={15} /></Button><Button icon="success" className="action-green" onClick={()=>void planAction('close')}>{active?'Clôturer':'Réactiver'}<Icon name="right" size={15} /></Button></Panel><Panel title="ÉQUIPE DE CRISE" action={<TextLink onClick={()=>openModal({kind:'team'})}>Voir l’équipe</TextLink>} className="crisis-team">{team.map(([name,role],i)=><button className="team-person" key={name} onClick={()=>openModal({kind:'team'})}>{i===0?<Avatar />:<span className={`initial-avatar color-${i}`}>{name.split(' ').map(n=>n[0]).join('')}</span>}<span><strong>{name}</strong><small>{role}</small></span><i className="dot green" /><small>{i<4?'En ligne':i===4?'Absent':'Hors ligne'}</small></button>)}</Panel><Panel title="ÉVOLUTION DU SENTIMENT" className="crisis-sentiment"><LineChart values={[92,88,80,8,7,6,6]} labels={['12:00','','13:00','','14:00','','15:00']} color="#ff4c5b" tooltip={false} /><div className="crisis-drop">Chute brutale à 13:04<br />-68% en 18 min</div></Panel><Panel title="PLANS DE RÉPONSE" action={<TextLink onClick={()=>crisis?edit('crises',crisis):edit('crises')}>Gérer</TextLink>} className="response-plans">{['Plan Critique','Plan Média','Plan Communication','Plan Juridique'].map((name,i)=><button key={name} onClick={()=>crisis?edit('crises',crisis):edit('crises')}><span>{name}{i===0&&active?' (Actif)':''}</span><Badge status={i===0&&active?'critical':'ready'} subtle>{i===0&&active?'Actif':'Prêt'}</Badge></button>)}</Panel></aside></div><div className="war-room-status"><Icon name="shield" size={23} /><span>{active?'Mode War Room activé – Surveillance renforcée en cours':'Crise clôturée – Votre réputation reste sous surveillance'}</span><i className="dot green" /></div></div>;
}
