'use client';
import { useRef, useState } from 'react';
import { platformNames } from '@/lib/demo-data';
import { useWorkspace } from '../workspace-context';
import { PageHeading } from '../app-shell';
import { Avatar, Badge, Button, Icon, IconButton, Panel, PlatformIcon, Select, TextLink } from '../ui';
import { ChartPanel, Donut, LineChart, scoreParts, SentimentPanel, TopicBars, WordCloud } from '../charts';
import { MentionMetrics, MiniMentions } from './dashboard';
import { QuickAnalysis } from './mentions';

export function ProfileView() {
  const { data, edit, navigate, generateReport, analyze, analyzing, save, notify, detail, refresh } = useWorkspace();
  const [tab,setTab] = useState('Informations générales'), [expanded,setExpanded] = useState(false), [uploading,setUploading] = useState(false);
  const uploadRef = useRef<HTMLInputElement>(null);
  const profile = data.profile[0];
  if (!profile) return null;
  const tabs = ['Informations générales','Activité en ligne','Médias & Articles','Statistiques','Relations','Historique'];
  async function upload(file?: File) {
    if(!file)return;setUploading(true);
    try {const form=new FormData();form.append('photo',file);const response=await fetch('/api/profile-photo',{method:'POST',body:form});const result=await response.json();if(!response.ok)throw new Error(result.error);await refresh();notify('Votre photo de profil a été enregistrée.');}catch(error){notify(error instanceof Error?error.message:'Impossible d’enregistrer la photo.',true);}finally{setUploading(false);}
  }
  return <div className="section-page profile-page"><div className="breadcrumb"><button onClick={()=>navigate('dashboard')}>Accueil</button><Icon name="right" size={12} /><span>Profils</span><Icon name="right" size={12} /><strong>Arnaud Kenne</strong></div><div className="profile-titlebar"><Button icon="back" onClick={()=>navigate('dashboard')}>Retour</Button><h1>Profil de personnalité</h1><Badge status="positive">Actif</Badge><span>Dernière mise à jour : 12 sept. 2026 – 14:32</span><div><Button icon="edit" onClick={()=>edit('profile',profile)}>Modifier le profil</Button><Button icon="download" onClick={()=>void generateReport('Rapport de personnalité')}>Générer un rapport</Button><Button variant="primary" icon="eye" onClick={async()=>{const result=await save('profile',{active:!profile.active},profile.id);if(result)notify(profile.active?'Surveillance mise en pause.':'Surveillance activée.');}}>{profile.active?'Surveiller':'Reprendre'}</Button><IconButton name="more" label="Informations du profil" className="bordered" onClick={()=>detail(profile)} /></div></div>
    <div className="profile-overview"><div className="profile-photo"><div className="profile-photo-bar"><Badge status="positive"><Icon name="success" size={14} />Profil vérifié</Badge></div><div className="profile-photo-main"><img src={profile.image||'/images/arnaud-kenne.jpg'} alt={profile.name} /></div><IconButton name={uploading?'loading':'camera'} label="Changer la photo de profil" onClick={()=>uploadRef.current?.click()} disabled={uploading} className="profile-photo-camera" /><input ref={uploadRef} type="file" accept="image/jpeg,image/png,image/webp" className="hidden-input" onChange={e=>void upload(e.target.files?.[0])} /></div><div className="profile-description"><h2>{profile.name}<span className="verified"><Icon name="check" size={12} /></span></h2><div className="profile-tags">{['Entrepreneur','Expert en IT','Formateur','Consultant','Leader'].map(t=><span key={t}>{t}</span>)}</div><p className={expanded?'expanded':''}>{profile.description}</p><button className="text-link" onClick={()=>setExpanded(!expanded)}>{expanded?'Voir moins':'Voir plus'}<Icon name="down" size={14} /></button></div><div className="profile-contact">{[['mail','Email',profile.email],['phone','Téléphone',profile.phone],['pin','Localisation',`${profile.city}, ${profile.country}`],['globe','Site web',profile.url?.replace('https://','')]].map(([icon,label,value])=><div key={label}><Icon name={icon||'user'} size={17} /><span><small>{label}</small><strong>{value}</strong></span></div>)}<div><Icon name="users" size={17} /><span><small>Réseaux sociaux</small><div className="social-links">{['linkedin','facebook','x','instagram','youtube'].map(p=><button key={p} onClick={()=>navigate(`mentions?source=${p}`)} aria-label={platformNames[p]}><PlatformIcon platform={p} size="small" /></button>)}<span className="social-more">+2</span></div></span></div></div><Panel title="Score global de réputation" className="profile-score"><div className="profile-score-layout"><div className="profile-score-donut"><Donut score={78} /></div><div className="profile-score-statuses">{scoreParts.map(([label,value],i)=><div key={label} className="profile-score-row"><span><i className={`dot ${i===5?'red':i===2?'blue':i===4?'yellow':'green'}`} />{label}</span></div>)}</div><div className="profile-score-values">{scoreParts.map(([label,value],i)=><div key={label} className="profile-score-row"><strong>{value}<small>/100</small></strong></div>)}</div></div></Panel></div>
    <MentionMetrics last="risk" compact />
    <div className="profile-tabs" role="tablist">{tabs.map(t=><button role="tab" aria-selected={tab===t} onClick={()=>setTab(t)} className={tab===t?'selected':''} key={t}>{t}</button>)}</div>
    {tab==='Informations générales'?<><div className="profile-information"><Panel title="Biographie" icon="user" className="profile-biography"><p>Arnaud Kenne est un entrepreneur camerounais passionné par les technologies de l’information et de l’innovation. Il est le Directeur de Ghostroar Digital, une entreprise spécialisée dans le développement de solutions web et mobiles, la cybersécurité, le marketing digital et la transformation numérique.</p><p>Il est également le Fondateur de l’IFPTII, un institut de formation professionnelle dans les domaines de l’informatique, du digital et de l’innovation, contribuant à la formation des jeunes talents en Afrique.</p>{expanded&&<p>{profile.description}</p>}<TextLink onClick={()=>setExpanded(!expanded)}>{expanded?'Voir moins':'Voir plus'}</TextLink></Panel><Panel title="Réseaux sociaux" icon="users" className="profile-networks">{[['linkedin','12 500'],['facebook','28 700'],['x','15 300'],['instagram','18 900'],['youtube','7 800'],['tiktok','11 200']].map(([platform,count])=><button onClick={()=>navigate(`mentions?source=${platform}`)} key={platform}><PlatformIcon platform={platform} size="small" /><span>{platformNames[platform]}</span><small>{count} abonnés</small><Icon name="right" size={13} /></button>)}</Panel><Panel title="Actions rapides" className="profile-quick-actions"><Button variant="primary" icon="trend" onClick={()=>navigate('mentions')}>Voir les mentions récentes</Button><Button icon="search" busy={analyzing} onClick={()=>void analyze()}>Analyser la réputation</Button><Button icon="bell" onClick={()=>navigate('alertes')}>Gérer les alertes</Button><Button icon="download" onClick={()=>void generateReport()}>Créer un rapport</Button><Button icon="edit" onClick={()=>edit('profile',profile)}>Modifier le profil</Button></Panel><Panel title="Informations clés" icon="lock" className="profile-key-info">{[['user','Nom complet',profile.name],['work','Profession',profile.role],['building','Domaine',profile.domain],['building','Entreprise',profile.company],['work','Fonction','Directeur Général'],['globe','Pays',profile.country],['pin','Ville',profile.city],['languages','Langues',profile.languages]].map(([icon,label,value])=><div key={label}><Icon name={icon||'user'} size={14} /><span>{label} :</span><strong>{value}</strong></div>)}</Panel></div><div className="profile-bottom"><ChartPanel title="Évolution du score de réputation" /><SentimentPanel /><MiniMentions limit={4} /><Panel title="Tendances clés" icon="users" className="profile-trends">{['IA & innovation','Formation des jeunes','Cybersécurité','Digitalisation en Afrique','Projets sociaux'].map(t=><button onClick={()=>navigate('analyse')} key={t}><span>{t}</span><Icon name="up" size={15} /></button>)}</Panel></div></>:
      <div className="profile-tab-content">{tab==='Activité en ligne'?<MiniMentions limit={10} />:tab==='Statistiques'?<div className="profile-statistics"><ChartPanel title="Évolution du score de réputation" /><SentimentPanel /></div>:tab==='Médias & Articles'?<Panel title="Dernières publications et articles" icon="file">{data.publications.map(post=><button className="profile-content-row" key={post.id} onClick={()=>detail(post)}><PlatformIcon platform={post.platform} /><span><strong>{post.name}</strong><small>{post.description}</small></span><Badge status={post.status} subtle /><Icon name="right" size={15} /></button>)}</Panel>:tab==='Relations'?<Panel title="Votre réseau média" icon="users">{data.contacts.map(contact=><button className="profile-content-row" key={contact.id} onClick={()=>detail(contact)}><PlatformIcon platform={contact.platform} /><span><strong>{contact.name} – {contact.company}</strong><small>{contact.role}</small></span><Badge status={contact.sentiment} subtle /><Icon name="right" size={15} /></button>)}</Panel>:<Panel title="Historique de votre réputation" icon="clock">{data.reports.map(report=><button className="profile-content-row" key={report.id} onClick={()=>detail(report)}><Icon name="file" size={25} /><span><strong>{report.name}</strong><small>Rapport enregistré le {new Date(report.date||Date.now()).toLocaleDateString('fr-FR')}</small></span><Icon name="right" size={15} /></button>)}</Panel>}</div>}
  </div>;
}

export function AnalysisView() {
  const { data, analyze, analyzing, exportData, detail, navigate } = useWorkspace();
  const [period,setPeriod]=useState('30');
  return <div className="section-page analysis-page"><PageHeading title="Analyse IA" icon="brain" subtitle="Exploitez la puissance de l’intelligence artificielle pour une analyse approfondie et prédictive de la réputation."><div className="period-control"><Icon name="calendar" size={19} /><Select value={period} onChange={e=>setPeriod(e.target.value)} aria-label="Période d’analyse"><option value="30">Période : 01 sept. 2026 → 30 sept. 2026</option><option value="7">7 derniers jours</option><option value="90">90 derniers jours</option></Select></div><Button variant="primary" icon="bolt" busy={analyzing} onClick={()=>void analyze()}>{analyzing?'Analyse en cours':'Analyser'}</Button><Button icon="download" onClick={()=>void exportData('reports')}>Exporter</Button></PageHeading>
    <div className="ai-stat-grid"><div className="ai-stat ai-score"><h3>Score global IA</h3><div><Donut score={78} small /><span><Icon name="brain" size={30} /><b className="text-green"><Icon name="up" size={17} />+6,3%</b></span></div></div><div className="ai-stat"><h3>Analyse des sentiments</h3><div><span className="ai-stat-icon green"><Icon name="smile" size={35} /></span><span><strong>70,1%</strong><b className="text-green">Positifs</b><em className="text-green"><Icon name="up" size={15} />+8,2%</em></span></div></div><div className="ai-stat ai-negative"><h3>Tonalité des mentions</h3><div><span className="ai-stat-icon red"><Icon name="sound" size={34} /></span><span><strong>12,7%</strong><b>Négatives</b><em className="text-red"><Icon name="decrease" size={15} />-3,5%</em></span></div></div><div className="ai-stat ai-risk"><h3>Prédiction de risque</h3><div><span className="ai-stat-icon red"><Icon name="warning" size={34} /></span><span><b className="text-green">FAIBLE</b><strong className="risk-percent">12,3%</strong></span></div><div className="risk-bar"><i /></div></div><div className="ai-stat"><h3>Indice d’influence</h3><div><span className="ai-stat-icon dark-green"><Icon name="bars" size={34} /></span><span><strong>87<small>/100</small></strong><em className="text-green"><Icon name="up" size={16} />+7,1%</em></span></div></div></div>
    <div className="ai-chart-row"><ChartPanel key={period} title="Évolution du score IA" icon="brain" multi /><SentimentPanel /><QuickAnalysis detailed /></div>
    <div className="ai-insight-row"><Panel title="Top des sujets analysés" icon="content" action={<TextLink onClick={()=>navigate('mentions')} />}><TopicBars numbered /></Panel><Panel title="Nuage de mots-clés" icon="brain"><WordCloud /></Panel><Panel title="Analyse des tendances" icon="content" action={<TextLink onClick={()=>void analyze()}>Voir détails</TextLink>} className="ai-trends">{[['Mentions globales','+12,5%','#00ec83'],['Sentiment positif','+8,2%','#119bf7'],['Sentiment négatif','-3,5%','#ff455e'],['Engagement','+15,7%','#b75cef']].map(([label,value,color],i)=><div key={label}><span>{label}</span><div className="tiny-sparkline"><LineChart values={[22,16,38,25,30,48,33,38,65]} color={color} max={80} compact /></div><strong className={i===2?'text-red':'text-green'}><Icon name={i===2?'decrease':'up'} size={14} />{value}</strong></div>)}</Panel></div>
    <div className="ai-footer-row"><Panel title="Rapport d’analyse IA" icon="brain" className="ai-report"><p>L’IA a analysé 2 487 mentions provenant de 18 sources. La réputation globale est en amélioration, avec une forte présence de contenus positifs liés à l’innovation et à la cybersécurité.</p><Button variant="green-outline" icon="file" onClick={()=>{const report=[...data.reports].reverse().find(r=>r.category==='Analyse IA');if(report)detail(report);else void analyze();}}>Voir le rapport détaillé <Icon name="arrow" size={17} /></Button></Panel><Panel title="Recommandations de l’IA" icon="bulb" className="ai-recommendations">{['Renforcer la communication sur les projets innovants','Surveiller les contenus liés à la cybersécurité','Augmenter la présence sur les réseaux éducatifs','Mettre en avant les témoignages clients'].map(text=><div key={text}><Icon name="check" size={18} /><span>{text}</span></div>)}</Panel><Panel title="Prédiction (30 jours)" icon="chart" className="ai-forecast"><div><strong>82<span>/100</span></strong><Badge status="positive">Stable · +3,2%</Badge></div><LineChart compact values={[25,31,37,35,50,58,49,56,62,75,87]} max={100} /></Panel></div>
  </div>;
}
