'use client';
import { useState } from 'react';
import { formatNumber } from '@/lib/types';
import { useWorkspace } from '../workspace-context';
import { PageHeading } from '../app-shell';
import { Badge, Button, EmptyState, Icon, IconButton, Panel, PlatformIcon, TextLink, Toggle } from '../ui';
import { Donut } from '../charts';

export function SourcesView() {
  const { data, edit, save, detail, openModal, navigate, notify } = useWorkspace();
  const [category, setCategory] = useState('all');
  const active = data.sources.filter(source => source.active).length;
  const filtered = data.sources.filter(source => category === 'all' || source.category === category);
  const categories = [['all','Toutes','layers'],['social','Réseaux sociaux','users'],['media','Médias & News','content'],['search','Moteurs de recherche','search'],['web','Sites web','globe'],['other','Autres','file']];
  return <div className="section-page sources-page"><div className="sources-layout"><div className="sources-main"><PageHeading title="Sources de surveillance" icon="radar" subtitle="Gérez et configurez toutes les sources de collecte de données pour surveiller efficacement la présence et la réputation de vos personnalités, entreprises ou marques sur le web et les réseaux sociaux."><div className="source-monitor"><span><strong><i className="dot green" />Surveillance active</strong><small>{active} sources connectées</small></span><div className="source-monitor-ring"><svg viewBox="0 0 90 90"><circle cx="45" cy="45" r="37" fill="none" stroke="#075345" strokeWidth="7" /><circle cx="45" cy="45" r="37" fill="none" stroke="#00ee87" strokeWidth="7" strokeDasharray={`${232 * active / Math.max(1,data.sources.length)} 232`} transform="rotate(-90 45 45)" /></svg><span><b>{active}/{data.sources.length}</b><small>Sources</small></span></div></div></PageHeading>
    <div className="source-tabs" role="tablist" aria-label="Catégories de sources">{categories.map(([key,label,icon])=><button role="tab" aria-selected={category===key} className={category===key?'selected':''} onClick={()=>setCategory(key)} key={key}>{key!=='all' && <Icon name={icon} size={17} />}{label} ({key==='all'?data.sources.length:data.sources.filter(source=>source.category===key).length})</button>)}</div>
    <div className="source-grid">{filtered.slice(0,12).map(source=><article className="source-card" key={source.id}><div className="source-card-top"><PlatformIcon platform={source.platform} size="large" /><div><button onClick={()=>detail(source)} className="source-name">{source.name}</button><p>{source.description}</p></div><IconButton name="more" label={`Gérer ${source.name}`} onClick={()=>edit('sources',source)} /></div><div className={`source-connection ${source.status==='partial'?'partial':''} ${!source.active?'inactive':''}`}><span><i className={`dot ${source.status==='partial'?'yellow':source.active?'green':'muted'}`} />{source.status==='partial'?'Partiellement':source.active?'Connectée':'Déconnectée'}</span><Toggle label={`${source.active?'Désactiver':'Activer'} ${source.name}`} checked={Boolean(source.active)} onChange={async()=>{const result=await save('sources',{active:!source.active,status:source.active?'inactive':'connected'},source.id);if(result)notify(`${source.name} ${source.active?'désactivée':'activée'}.`);}} /></div><div className="source-card-bottom"><Icon name="mentions" size={19} /><span><strong>{formatNumber(source.count||0)}</strong><small>mentions/jour</small></span><b><Icon name="up" size={17} />+{source.growth||0}%</b></div></article>)}</div>{!filtered.length && <EmptyState title="Aucune source dans cette catégorie" message="Ajoutez une source pour enrichir votre surveillance." icon="radar" action={<Button variant="primary" icon="plus" onClick={()=>edit('sources')}>Ajouter une source</Button>} />}</div>
    <aside className="sources-aside"><Panel title="Statistiques globales" icon="bars"><div className="source-global-stats">{[['Sources actives',active,'green','radar'],['Sources inactives',data.sources.length-active,'red','alert'],['Total des sources',data.sources.length,'purple','layers'],['Mentions collectées','71 870','purple','mentions'],['Taux de couverture','95%','green','shield']].map(([name,value,color,icon])=><div key={name}><Icon name={String(icon)} size={17} className={`text-${color}`} /><span>{name}</span><strong className={`text-${color}`}>{value}</strong></div>)}</div></Panel><Panel title="Répartition des mentions" icon="chart" className="source-distribution"><Donut total="71 870" label="Total" source /><div className="source-distribution-legend">{[['Réseaux sociaux','62%','blue'],['Médias & News','18%','purple'],['Sites web','10%','yellow'],['Forums','6%','violet'],['Autres','4%','muted']].map(([name,value,color])=><div key={name}><i className={`dot ${color}`} /><span>{name}</span><strong>{value}</strong></div>)}</div></Panel><Panel title="Activité récente" icon="chart" action={<TextLink onClick={()=>navigate('mentions')} />} className="source-activity">{[['x','Nouveau mention sur X','Il y a 2 min','+1'],['google','Article publié sur Google News','Il y a 8 min','+3'],['youtube','Nouveau commentaire YouTube','Il y a 15 min','+2'],['facebook','Mention détectée sur Facebook','Il y a 27 min','+5'],['tiktok','Publication TikTok analysée','Il y a 42 min','+1']].map(([platform,title,time,count])=><button key={platform} onClick={()=>navigate(`mentions?source=${platform}`)}><PlatformIcon platform={platform} size="small" /><span><strong>{title}</strong><small>{time}</small></span><Badge status="connected">{count}</Badge></button>)}</Panel></aside></div>
    <div className="pro-tip"><div className="tip-bulb"><Icon name="bulb" size={31} /></div><span><strong>Conseil pro</strong><p>Pour une meilleure couverture, ajoutez des sources locales et des médias spécialisés dans votre domaine d’activité.</p></span><Button variant="green-outline" onClick={()=>openModal({kind:'recommendations'})}>Voir les recommandations <Icon name="arrow" size={17} /></Button></div></div>;
}
