'use client';
import { useState, type FormEvent } from 'react';
import { AppShell, PageHeading } from '@/components/app-shell';
import { useWorkspace } from '@/components/workspace-context';
import { Avatar, Badge, Button, Icon, Panel, PlatformIcon, Toggle } from '@/components/ui';
import type { Entity } from '@/lib/types';
import { platformNames } from '@/lib/demo-data';

const tabs = ['Compte', 'Notifications', 'Sécurité', 'Intégrations', 'Abonnement', 'Préférences'];
export default function ParametresPage() {
  const { data, user, save, notify, openModal, navigate, edit } = useWorkspace();
  const settings = data.settings[0] || { id: '', type: 'settings' as const, name: 'Préférences du compte', languages: 'Français', emailAlerts: true, pushAlerts: true, digest: false, status: 'active' };
  const profile = data.profile[0];
  const [tab, setTab] = useState('Compte');
  const [form, setForm] = useState({ name: profile?.name || user.name, email: profile?.email || user.email, phone: profile?.phone || '', city: profile?.city || '', country: profile?.country || '', languages: settings.languages || 'Français', timezone: 'UTC+1 Afrique de l’Ouest', emailAlerts: settings.emailAlerts !== false, pushAlerts: settings.pushAlerts !== false, digest: !!settings.digest, showSensitive: false });
  const [busy, setBusy] = useState(false);
  const set = (key: string, value: string | boolean) => setForm(prev => ({ ...prev, [key]: value }));
  async function submit(event: FormEvent) {
    event.preventDefault(); setBusy(true);
    const [savedProfile, savedSettings] = await Promise.all([
      save('profile', { name: form.name, email: form.email, phone: form.phone, city: form.city, country: form.country, languages: form.languages }, profile?.id),
      save('settings', { ...settings, name: settings.name || 'Préférences du compte', languages: form.languages, emailAlerts: form.emailAlerts, pushAlerts: form.pushAlerts, digest: form.digest }, settings.id || undefined),
    ]);
    setBusy(false);
    if (savedProfile && savedSettings) notify('Vos paramètres ont été enregistrés.');
  }
  async function toggleSetting(key: 'emailAlerts' | 'pushAlerts' | 'digest') {
    const next = !form[key]; set(key, next);
    const result = await save('settings', { ...settings, [key]: next, name: settings.name || 'Préférences du compte' }, settings.id || undefined);
    if (result) notify('Préférence de notification mise à jour.'); else set(key, !next);
  }
  const [showAddForm, setShowAddForm] = useState(false);
  const [newPlatform, setNewPlatform] = useState('');
  const [newName, setNewName] = useState('');
  const addIntegration = async () => {
    if (!newPlatform || !newName.trim()) return;
    if (data.integrations.some(i => i.platform === newPlatform && i.name.toLowerCase() === newName.trim().toLowerCase())) { notify('Cette intégration existe déjà.', true); return; }
    const saved = await save('integrations', { name: newName.trim(), platform: newPlatform, connected: false });
    if (!saved) return;
    setNewPlatform('');
    setNewName('');
    setShowAddForm(false);
    notify(`${newName.trim()} a été enregistré dans vos intégrations.`);
  };
  return <AppShell section="parametres"><div className="section-page settings-page">
    <PageHeading title="Paramètres" subtitle="Dernière mise à jour : 24 mai 2025 à 10:42"><span className="settings-save-status"><i className="dot green"/> Vos préférences sont synchronisées</span></PageHeading>
    <div className="settings-tabs" role="tablist" aria-label="Sections des paramètres">{tabs.map(item=><button key={item} role="tab" aria-selected={tab===item} className={tab===item?'selected':''} onClick={()=>setTab(item)}>{item}</button>)}</div>
    {tab==='Compte' && <form className="settings-layout" onSubmit={submit}><section className="settings-main"><Panel title="Compte" icon="user"><p className="settings-description">Gérez vos informations personnelles et préférences de compte.</p><div className="settings-profile"><Avatar size="hero" src={profile?.image}/><div><h2>{form.name}</h2><p>{form.email}</p><Badge status="active" subtle>Administrateur</Badge></div><Button icon="edit" onClick={()=>profile && edit('profile',profile)}>Modifier le profil</Button></div><div className="settings-fields"><label>Nom complet<input required value={form.name} onChange={e=>set('name',e.target.value)}/></label><label>Email<input type="email" required value={form.email} onChange={e=>set('email',e.target.value)}/></label><label>Téléphone<input value={form.phone} onChange={e=>set('phone',e.target.value)}/></label><label>Localisation<input value={[form.city,form.country].filter(Boolean).join(', ')} onChange={e=>{const [city,...country]=e.target.value.split(',');setForm(f=>({...f,city:city.trim(),country:country.join(',').trim()}));}}/></label><label>Langue<select value={form.languages} onChange={e=>set('languages',e.target.value)}><option>Français</option><option>English</option><option>Español</option></select></label><label>Fuseau horaire<select value={form.timezone} onChange={e=>set('timezone',e.target.value)}><option>UTC+1 Afrique de l’Ouest</option><option>UTC+0 Europe de l’Ouest</option><option>UTC-5 Amérique</option></select></label></div><div className="settings-toggles"><div><span><strong>Recevoir les notifications par email</strong><small>Alertes, rapports et mises à jour importantes</small></span><Toggle checked={form.emailAlerts} onChange={()=>void toggleSetting('emailAlerts')} label="Notifications par email"/></div><div><span><strong>Recevoir les notifications push</strong><small>Alertes en temps réel sur mobile</small></span><Toggle checked={form.pushAlerts} onChange={()=>void toggleSetting('pushAlerts')} label="Notifications push"/></div><div><span><strong>Afficher les données sensibles</strong><small>Autoriser l’affichage des informations confidentielles</small></span><Toggle checked={form.showSensitive} onChange={()=>set('showSensitive',!form.showSensitive)} label="Afficher les données sensibles"/></div></div><Button type="submit" variant="primary" icon="save" busy={busy}>Enregistrer les modifications</Button></Panel></section>
    <aside className="settings-aside"><Panel title="Sécurité" icon="shield"><button className="settings-row" onClick={()=>notify('L’authentification à deux facteurs est activée.')}><Icon name="shield"/><span><strong>Authentification à deux facteurs (2FA)</strong><small className="text-green">Activée</small></span><Icon name="right"/></button><button className="settings-row" onClick={()=>notify('Vous êtes connecté à une session sécurisée.')}><Icon name="user"/><span><strong>Sessions actives</strong><small>1 session connectée</small></span><Icon name="right"/></button><button className="settings-row" onClick={()=>openModal({kind:'password'})}><Icon name="clock"/><span><strong>Changer le mot de passe</strong><small>Gérez votre accès au compte</small></span><Icon name="right"/></button></Panel><Panel title="Abonnement actuel" icon="star" className="subscription-panel"><div className="subscription-layout"><div className="subscription-summary"><p>Votre plan et détails de facturation.</p><Badge status="active" subtle>Pro</Badge><span>Prochaine facturation : 24 novembre 2026</span><strong>250 000 FCFA <small>/mois</small></strong></div><Button className="change-plan-button" onClick={()=>navigate('offres')}>Changer de plan <Icon name="up" size={15}/></Button></div></Panel><Panel title="Intégrations connectées" icon="puzzle"><p className="settings-description">Gérez vos connexions aux réseaux et services.</p>{data.integrations.map(integration =><button className="integration-row" key={integration.id} onClick={()=>notify(integration.connected?`${integration.name} est connecté.`:`Connectez ${integration.name} depuis votre espace intégrations.`)}><PlatformIcon platform={integration.platform} size="small"/><span>{integration.name}</span><small className={integration.connected?'text-green':''}>{integration.connected?'Connecté':'Déconnecté'}</small><Icon name={integration.connected?'success':'right'} size={17}/></button>)}{showAddForm ? (<div className="integration-form"><select value={newPlatform} onChange={e=>setNewPlatform(e.target.value)}><option value="">Sélectionner une plateforme</option>{Object.entries(platformNames).map(([key,label])=> <option key={key} value={key}>{label}</option>)}</select><input value={newName} onChange={e=>setNewName(e.target.value)} placeholder="Nom de l'intégration"/><Button onClick={addIntegration}>Ajouter</Button><Button variant="ghost" onClick={()=>setShowAddForm(false)}>Annuler</Button></div>) : (<Button icon="plus" onClick={()=>setShowAddForm(true)} style={{marginTop:'.5rem'}}>Ajouter une intégration</Button>)}</Panel></aside></form>}
    {tab==='Notifications' && <Panel title="Préférences de notification" icon="bell"><p className="settings-description">Choisissez les événements pour lesquels vous souhaitez être averti.</p>{(['emailAlerts','pushAlerts','digest'] as const).map((key,i)=><div className="settings-toggles" key={key}><div><span><strong>{['Notifications par email','Notifications push','Synthèse hebdomadaire'][i]}</strong><small>{['Alertes importantes et rapports','Alertes urgentes en temps réel','Recevez un récapitulatif chaque lundi'][i]}</small></span><Toggle checked={form[key]} onChange={()=>void toggleSetting(key)} label={['Notifications par email','Notifications push','Synthèse hebdomadaire'][i]}/></div></div>)}<Button variant="primary" icon="save" onClick={()=>notify('Vos préférences de notification sont enregistrées.')}>Enregistrer les préférences</Button></Panel>}
    {tab==='Sécurité' && <Panel title="Sécurité du compte" icon="shield"><p className="settings-description">Protégez vos accès et vérifiez vos sessions actives.</p><button className="settings-row" onClick={()=>notify('L’authentification à deux facteurs est activée.')}><Icon name="shield"/><span><strong>Authentification à deux facteurs (2FA)</strong><small className="text-green">Activée</small></span><Icon name="right"/></button><button className="settings-row" onClick={()=>notify('Vous êtes connecté à une session sécurisée.')}><Icon name="user"/><span><strong>Sessions actives</strong><small>1 session connectée</small></span><Icon name="right"/></button><Button icon="lock" onClick={()=>openModal({kind:'password'})}>Changer le mot de passe</Button></Panel>}
    {tab==='Intégrations' && <Panel title="Intégrations connectées" icon="puzzle"><p className="settings-description">Gérez vos connexions aux réseaux et services.</p>{data.integrations.map(integration =><button className="integration-row" key={integration.id} onClick={()=>notify(integration.connected?`${integration.name} est connecté.`:`Connectez ${integration.name} depuis votre espace intégrations.`)}><PlatformIcon platform={integration.platform} size="small"/><span>{integration.name}</span><small className={integration.connected?'text-green':''}>{integration.connected?'Connecté':'Déconnecté'}</small><Icon name={integration.connected?'success':'right'} size={17}/></button>)}{showAddForm ? (<div className="integration-form"><select value={newPlatform} onChange={e=>setNewPlatform(e.target.value)}><option value="">Sélectionner une plateforme</option>{Object.entries(platformNames).map(([key,label])=> <option key={key} value={key}>{label}</option>)}</select><input value={newName} onChange={e=>setNewName(e.target.value)} placeholder="Nom de l'intégration"/><Button onClick={addIntegration}>Ajouter</Button><Button variant="ghost" onClick={()=>setShowAddForm(false)}>Annuler</Button></div>) : (<Button icon="plus" onClick={()=>setShowAddForm(true)} style={{marginTop:'.5rem'}}>Ajouter une intégration</Button>)}</Panel>}
    {tab==='Abonnement' && <Panel title="Abonnement actuel" icon="star"><div className="subscription-summary"><Badge status="active" subtle>Pro</Badge><p>Votre plan et détails de facturation.</p><strong>250 000 FCFA <small>/mois</small></strong></div><Button variant="primary" onClick={()=>navigate('offres')}>Découvrir nos offres <Icon name="arrow"/></Button></Panel>}
    {tab==='Préférences' && <form className="settings-main" onSubmit={submit}><Panel title="Préférences de l’espace" icon="settings"><div className="settings-fields"><label>Langue<select value={form.languages} onChange={e=>set('languages',e.target.value)}><option>Français</option><option>English</option><option>Español</option></select></label><label>Fuseau horaire<select value={form.timezone} onChange={e=>set('timezone',e.target.value)}><option>UTC+1 Afrique de l’Ouest</option><option>UTC+0 Europe de l’Ouest</option><option>UTC-5 Amérique</option></select></label></div><Button type="submit" variant="primary" icon="save" busy={busy}>Enregistrer les préférences</Button></Panel></form>}
    <footer className="settings-footer"><span>GHOSTROAR REPUTATION v2.5.0 <i className="dot green"/> Plateforme e-réputation professionnelle</span><span>Besoin d’aide ? <a href="mailto:support@ghostroar.com">Contactez le support</a></span></footer>
  </div></AppShell>;
}
