'use client';
import { useState, useRef, type FormEvent } from 'react';
import type { Entity, ResourceType } from '@/lib/types';
import { platformNames } from '@/lib/demo-data';
import { useWorkspace } from './workspace-context';
import { Avatar, Badge, Button, EmptyState, Icon, IconButton, Modal, PlatformIcon, Select, Toggle } from './ui';

type Field = { key: string; label: string; type?: string; required?: boolean; options?: [string, string][]; full?: boolean };
const platforms = Object.entries(platformNames);
const statuses: [string, string][] = [['draft','Brouillon'],['scheduled','Programmé'],['published','Publié'],['archived','Archivé']];
const fields: Record<ResourceType, Field[]> = {
  sources: [{ key:'name',label:'Nom de la source',required:true },{ key:'platform',label:'Plateforme',options:platforms },{ key:'url',label:'Adresse URL',type:'url',required:true,full:true },{ key:'category',label:'Catégorie',options:[['social','Réseaux sociaux'],['media','Médias & News'],['search','Moteurs de recherche'],['web','Sites web'],['other','Autres']] },{ key:'status',label:'État de la connexion',options:[['connected','Connectée'],['partial','Partiellement connectée'],['inactive','Déconnectée']] },{ key:'description',label:'Description',type:'textarea',full:true },{ key:'image',label:'Logo',type:'file' }],
  mentions: [{ key:'name',label:'Contenu de la mention',required:true,type:'textarea',full:true },{ key:'platform',label:'Source',options:platforms },{ key:'author',label:'Auteur / Canal',required:true },{ key:'sentiment',label:'Sentiment',options:[['positive','Positif'],['neutral','Neutre'],['negative','Négatif']] },{ key:'score',label:'Score (0 à 100)',type:'number' },{ key:'category',label:'Sujet' },{ key:'url',label:'Lien vers la mention',type:'url' }],
  alerts: [{ key:'name',label:'Titre de l’alerte',required:true,full:true },{ key:'description',label:'Description',type:'textarea',full:true },{ key:'severity',label:'Sévérité',options:[['critical','Critique'],['high','Élevée'],['medium','Moyenne'],['low','Basse'],['info','Information']] },{ key:'status',label:'Statut',options:[['unread','Non lue'],['in_progress','En cours'],['resolved','Résolue'],['archived','Archivée']] },{ key:'platform',label:'Source',options:platforms },{ key:'assignee',label:'Assignée à',options:[['','Non assignée'],['Arnaud Kenne','Arnaud Kenne'],['Camille Dubois','Camille Dubois'],['Julien Moreau','Julien Moreau'],['Sophie Leroy','Sophie Leroy']] }],
  publications: [{ key:'name',label:'Titre de la publication',required:true,full:true },{ key:'description',label:'Contenu',type:'textarea',required:true,full:true },{ key:'platform',label:'Plateforme',options:platforms },{ key:'status',label:'Statut',options:statuses },{ key:'date',label:'Date de publication',type:'datetime-local',full:true }],
  contacts: [{ key:'name',label:'Nom complet',required:true },{ key:'company',label:'Média / Organisation',required:true },{ key:'email',label:'Adresse email',type:'email',required:true },{ key:'phone',label:'Téléphone',type:'tel' },{ key:'role',label:'Fonction' },{ key:'category',label:'Type de média',options:[['Presse','Presse'],['TV','Télévision'],['Radio','Radio'],['Web','Web'],['Influenceur','Influenceur']] },{ key:'country',label:'Pays' },{ key:'sentiment',label:'Sentiment',options:[['positive','Positif'],['neutral','Neutre'],['negative','Négatif']] },{ key:'notes',label:'Notes de relation',type:'textarea',full:true }],
  reports: [{ key:'name',label:'Titre du rapport',required:true,full:true },{ key:'category',label:'Type de rapport',options:[['Réputation','Réputation'],['Analyse','Analyse'],['Mensuel','Mensuel'],['Crise','Gestion de crise']] },{ key:'date',label:'Date',type:'date' },{ key:'description',label:'Contenu du rapport',type:'textarea',full:true }],
  rules: [{ key:'name',label:'Nom de la règle',required:true,full:true },{ key:'category',label:'Déclencheur',options:[['sentiment','Sentiment négatif'],['volume','Volume de mentions'],['identity','Usurpation d’identité']] },{ key:'severity',label:'Sévérité',options:[['critical','Critique'],['high','Élevée'],['medium','Moyenne'],['low','Basse']] },{ key:'description',label:'Conditions et seuil de déclenchement',type:'textarea',required:true,full:true },{ key:'active',label:'Activer cette règle',type:'checkbox',full:true }],
  crises: [{ key:'name',label:'Nom de la crise',required:true,full:true },{ key:'description',label:'Description de la situation',type:'textarea',full:true },{ key:'status',label:'Statut',options:[['active','Active'],['in_progress','En cours'],['closed','Clôturée']] },{ key:'severity',label:'Sévérité',options:[['critical','Critique'],['high','Élevée'],['medium','Moyenne']] },{ key:'progress',label:'Avancement du plan (%)',type:'number' },{ key:'assignee',label:'Équipe assignée' },{ key:'notes',label:'Plan de réponse',type:'textarea',full:true }],
  profile: [{ key:'name',label:'Nom complet',required:true,full:true },{ key:'role',label:'Profession',required:true },{ key:'company',label:'Entreprise' },{ key:'email',label:'Adresse email',type:'email' },{ key:'phone',label:'Téléphone',type:'tel' },{ key:'city',label:'Ville' },{ key:'country',label:'Pays' },{ key:'url',label:'Site web',type:'url' },{ key:'languages',label:'Langues' },{ key:'domain',label:'Domaines d’expertise',full:true },{ key:'description',label:'Biographie',type:'textarea',full:true }],
  appointments: [{ key:'name',label:'Objet du rendez-vous',required:true,full:true },{ key:'author',label:'Contact',required:true },{ key:'company',label:'Média / Organisation' },{ key:'date',label:'Date et heure',type:'datetime-local',required:true },{ key:'email',label:'Email du contact',type:'email' },{ key:'status',label:'Statut',options:[['scheduled','Planifié'],['resolved','Terminé'],['archived','Annulé']] },{ key:'description',label:'Notes préparatoires',type:'textarea',full:true }],
  campaigns: [{ key:'name',label:'Nom de la campagne',required:true,full:true },{ key:'description',label:'Objectifs et message clé',required:true,type:'textarea',full:true },{ key:'status',label:'Statut',options:[['draft','Brouillon'],['active','Active'],['resolved','Terminée'],['archived','Archivée']] },{ key:'date',label:'Date de lancement',type:'date' },{ key:'assignee',label:'Responsable',full:true }],
  settings: [{ key:'name',label:'Nom des préférences',required:true },{ key:'emailAlerts',label:'Alertes par email',type:'checkbox' },{ key:'pushAlerts',label:'Notifications dans l’application',type:'checkbox' },{ key:'digest',label:'Synthèse hebdomadaire',type:'checkbox' }],
  integrations: [{ key:'name',label:'Nom de l’intégration',required:true },{ key:'platform',label:'Plateforme',options:platforms },{ key:'connected',label:'Connecté',type:'checkbox' }],
};
const resourceLabels: Record<ResourceType, string> = { sources:'une source',mentions:'une mention',alerts:'une alerte',publications:'un contenu',contacts:'un contact',reports:'un rapport',rules:'une règle',crises:'une crise',profile:'le profil',settings:'les préférences',appointments:'un rendez-vous',campaigns:'une campagne',integrations:'une intégration' };
const defaults: Record<ResourceType, Partial<Entity>> = { sources:{platform:'web',category:'web',status:'connected',active:true,count:0,growth:0},mentions:{platform:'facebook',sentiment:'positive',score:75,category:'Innovation technologique',time:'À l’instant'},alerts:{platform:'web',severity:'medium',status:'unread',time:'À l’instant'},publications:{platform:'linkedin',status:'draft',views:'—',likes:0,comments:0,score:0,image:'speaker'},contacts:{category:'Presse',sentiment:'neutral',country:'France',platform:'person',score:50,status:'active'},reports:{category:'Réputation',status:'ready'},rules:{category:'sentiment',severity:'medium',active:true},crises:{status:'active',severity:'critical',progress:0},profile:{},  settings:{},appointments:{status:'scheduled'},campaigns:{status:'draft',count:0},integrations:{connected:false} };
function Editor({ type, entity, preset }: { type: ResourceType; entity?: Entity; preset?: Partial<Entity> }) {
  const { save, closeModal, notify, openModal } = useWorkspace();
  const [form, setForm] = useState<Partial<Entity>>({ ...defaults[type], ...entity, ...preset });
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const [logoFile, setLogoFile] = useState<File | null>(null);
  const logoInputRef = useRef<HTMLInputElement>(null);
  const update = (key: string, value: string | number | boolean) => setForm(previous => ({ ...previous, [key]: value }));
  async function uploadLogo(sourceId: string, file: File) {
    const formData = new FormData();
    formData.append('logo', file);
    formData.append('sourceId', sourceId);
    const response = await fetch('/api/sources/logo', { method: 'POST', body: formData });
    const result = await response.json();
    if (!response.ok) throw new Error(result.error);
    return result.image as string;
  }
  async function submit(event: FormEvent) {
    event.preventDefault(); setError('');
    if (type === 'publications' && form.status === 'scheduled' && !form.date) { setError('Choisissez une date pour programmer cette publication.'); return; }
    setBusy(true);
    const values = { ...form, ...(entity?.image ? { image: entity.image } : {}) };
    if (type === 'sources') values.active = values.status !== 'inactive';
    const result = await save(type, values, entity?.id);
    if (result && logoFile) {
      try { await uploadLogo(result.id, logoFile); }
      catch { notify('La source a été créée, mais le logo n\'a pas pu être enregistré.', true); }
    }
    setBusy(false);
    if (result) { closeModal(); notify(entity ? 'Les modifications ont été enregistrées.' : 'Le nouvel élément a été créé.'); }
    else setError('Vérifiez les informations puis réessayez.');
  }
  function handleLogoChange(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0];
    if (!file) return;
    if (!['image/jpeg','image/png','image/webp'].includes(file.type) || file.size > 2 * 1024 * 1024) { notify('Choisissez une image JPG, PNG ou WebP de moins de 2 Mo.', true); return; }
    setLogoFile(file);
    if (entity?.id) {
      uploadLogo(entity.id, file).then(image => { setForm(prev => ({ ...prev, image })); }).catch(() => notify('Échec de l\'upload du logo.', true));
    }
  }
  return <form onSubmit={submit}><p className="form-intro">{entity ? 'Mettez à jour les informations ci-dessous.' : 'Renseignez les informations pour ajouter cet élément à votre espace.'}</p><div className="form-grid">{fields[type].map(field => <label className={`form-field ${field.full ? 'full' : ''} ${field.type === 'checkbox' ? 'checkbox-field' : ''} ${field.type === 'file' ? 'file-field' : ''}`} key={field.key}><span>{field.label}{field.required && <em> *</em>}</span>{field.type === 'checkbox' ? <Toggle label={field.label} checked={Boolean(form[field.key])} onChange={() => update(field.key, !form[field.key])} /> : field.options ? <Select value={String(form[field.key] ?? field.options[0][0])} onChange={e => update(field.key, e.target.value)}>{field.options.map(([value,label]) => <option value={value} key={value}>{label}</option>)}</Select> : field.type === 'textarea' ? <textarea rows={type === 'profile' || type === 'reports' ? 6 : 4} required={field.required} value={String(form[field.key] ?? '')} onChange={e => update(field.key, e.target.value)} placeholder={field.label} minLength={field.required ? 2 : undefined} /> : field.type === 'file' ? <div className="file-upload"><input ref={logoInputRef} type="file" accept="image/jpeg,image/png,image/webp" className="hidden-input" onChange={handleLogoChange} /><Button variant="outline" icon="upload" type="button" onClick={() => logoInputRef.current?.click()}>{form.image ? 'Changer le logo' : 'Choisir un logo'}</Button>{form.image && <img src={form.image as string} alt="Aperçu du logo" className="logo-preview" />}</div> : <input type={field.type || 'text'} value={String(form[field.key] ?? '').slice(0, field.type === 'datetime-local' ? 16 : field.type === 'date' ? 10 : undefined)} onChange={e => update(field.key, field.type === 'number' ? Number(e.target.value) : e.target.value)} required={field.required} minLength={field.required && !field.type ? 2 : undefined} min={field.type === 'number' ? 0 : undefined} max={field.key === 'score' || field.key === 'progress' ? 100 : undefined} placeholder={field.type === 'url' ? 'https://' : field.label} />}</label>)}</div>{error && <div className="form-error"><Icon name="alert" />{error}</div>}<div className="modal-footer">{entity && type !== 'profile' && type !== 'settings' && <Button variant="danger-ghost" icon="delete" type="button" onClick={() => openModal({ kind: 'delete', entity })}>Supprimer</Button>}<span className="spacer" /><Button type="button" onClick={closeModal}>Annuler</Button><Button variant="primary" icon="save" busy={busy} type="submit">{entity ? 'Enregistrer' : 'Créer'}</Button></div></form>;
}
function PasswordForm() {
  const { closeModal, notify } = useWorkspace();
  const [busy,setBusy] = useState(false), [error,setError] = useState('');
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = new FormData(event.currentTarget);
    if (form.get('password') !== form.get('confirmation')) { setError('Les mots de passe ne correspondent pas.'); return; }
    setBusy(true); setError('');
    try { const response = await fetch('/api/actions/password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({currentPassword:form.get('currentPassword'),password:form.get('password')})}); const result = await response.json(); if (!response.ok) throw new Error(result.error); closeModal(); notify('Votre mot de passe a été modifié.'); } catch(error) {setError(error instanceof Error ? error.message : 'Une erreur est survenue.');} finally {setBusy(false);}
  }
  return <form onSubmit={submit} className="stack-form">{[['currentPassword','Mot de passe actuel'],['password','Nouveau mot de passe'],['confirmation','Confirmer le nouveau mot de passe']].map(([key,label])=><label className="form-field" key={key}><span>{label}</span><input name={key} type="password" required minLength={8} maxLength={128} autoComplete={key === 'currentPassword' ? 'current-password' : 'new-password'} /></label>)}{error && <p className="form-error">{error}</p>}<Button variant="primary" icon="lock" busy={busy}>Modifier le mot de passe</Button></form>;
}
function ContactComposer({ entity }: { entity?: Entity }) {
  const { save, notify, closeModal } = useWorkspace();
  const [busy,setBusy] = useState(false);
  if (entity?.type === 'alerts') return <div className="support-dialog"><div className="support-big-icon"><Icon name="alert" size={42}/></div><h3>Signaler cette menace</h3><p>La source « {entity.name} » est prête à être signalée. Votre équipe peut transmettre le signalement à la plateforme concernée.</p>{entity.url && <a className="support-contact" href={entity.url} target="_blank" rel="noreferrer"><Icon name="external"/>Consulter la source<Icon name="arrow"/></a>}<Button variant="primary" icon="check" onClick={async()=>{const result=await save('alerts',{status:'in_progress',notes:`Signalement préparé le ${new Date().toLocaleDateString('fr-FR')}`},entity.id);if(result){closeModal();notify('Le signalement est enregistré. Transmettez-le à la plateforme source.');}}}>Enregistrer le signalement</Button></div>;
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy(true); const form = new FormData(event.currentTarget);
    const subject = String(form.get('subject')), message = String(form.get('message')), email = String(form.get('email'));
    const result = await save('publications',{name:subject,description:message,status:'draft',platform:'presse',category:'Communiqué',email});
    setBusy(false);
    if (result) { window.location.href = `mailto:${encodeURIComponent(email)}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(message)}`; closeModal(); notify('Brouillon enregistré. Votre messagerie est prête pour l’envoi.'); }
  }
  return <form className="stack-form" onSubmit={submit}><p className="form-intro">Préparez votre message. Un brouillon sera conservé dans vos contenus avant l’ouverture de votre messagerie.</p><label className="form-field"><span>Destinataire</span><input name="email" type="email" required defaultValue={entity?.email || ''} placeholder="contact@media.fr" /></label><label className="form-field"><span>Objet</span><input name="subject" required minLength={2} defaultValue={entity ? `Prise de contact — GHOSTROAR / ${entity.company || entity.name}` : 'Communiqué de presse — GHOSTROAR'} /></label><label className="form-field"><span>Votre message</span><textarea name="message" rows={7} required defaultValue={`Bonjour ${entity?.name || ''},\n\n`} /></label><Button variant="primary" icon="send" busy={busy}>Ouvrir dans ma messagerie</Button></form>;
}
export function GlobalDialogs() {
  const { modal, notice, clearNotice, closeModal, data, edit, detail, remove, openModal, save, notify, downloadReport, navigate } = useWorkspace();
  const [deleting,setDeleting] = useState(false);
  let title = '', body: React.ReactNode = null;
  if (modal) {
    const entity = modal.entity;
    if (modal.kind === 'editor' && modal.resource) { title = `${entity ? 'Modifier' : 'Ajouter'} ${resourceLabels[modal.resource]}`; body = <Editor key={`${modal.resource}-${entity?.id || 'new'}`} type={modal.resource} entity={entity} preset={modal.defaults} />; }
    else if (modal.kind === 'delete' && entity) { title = 'Supprimer cet élément ?'; body = <><div className="delete-warning"><Icon name="delete" size={34} /><h3>{entity.name}</h3><p>Cette action est définitive. L’élément sera supprimé de votre espace et de tous les tableaux associés.</p></div><div className="modal-footer"><Button onClick={closeModal}>Annuler</Button><Button variant="danger" icon="delete" busy={deleting} onClick={async()=>{setDeleting(true); const done=await remove(entity);setDeleting(false);if(done)closeModal();}}>Supprimer définitivement</Button></div></>; }
    else if (modal.kind === 'detail' && entity) { title = entity.type === 'reports' ? 'Rapport de réputation' : entity.type === 'mentions' ? 'Détail de la mention' : 'Détails'; body = <><div className="detail-heading"><PlatformIcon platform={entity.platform || (entity.type === 'reports' ? 'presse' : 'web')} size="large" /><div><h3>{entity.name}</h3><div className="detail-badges">{entity.sentiment && <Badge status={entity.sentiment} />}{entity.status && <Badge status={entity.status} subtle />}{entity.severity && <Badge status={entity.severity} subtle />}{entity.score !== undefined && <span className="text-green">{entity.score}/100</span>}</div></div></div>{entity.description && <p className={`detail-description ${entity.type === 'reports' ? 'report-content' : ''}`}>{entity.description}</p>}<dl className="detail-metadata">{[['Auteur',entity.author],['Source',platformNames[entity.platform || '']],['Email',entity.email],['Téléphone',entity.phone],['Entreprise',entity.company],['Assignée à',entity.assignee],['Catégorie',entity.category],['Date',entity.date ? new Date(entity.date).toLocaleDateString('fr-FR') : undefined],['Mentions collectées',entity.count]].filter(([,value])=>value !== undefined && value !== '').map(([label,value])=><div key={String(label)}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>{entity.notes && <div className="detail-note"><h4>Notes</h4><p>{entity.notes}</p></div>}{entity.url && <a className="external-link" href={entity.url} target="_blank" rel="noreferrer"><Icon name="external" size={15} />Ouvrir la source originale</a>}{entity.type === 'sources' && <p className="form-hint">Connecteur de démonstration. Les données proviennent de votre espace local.</p>}<div className="modal-footer"><Button icon="delete" variant="danger-ghost" onClick={()=>openModal({kind:'delete',entity})}>Supprimer</Button><span className="spacer" /><Button icon="edit" onClick={()=>edit(entity.type,entity)}>Modifier</Button>{entity.type === 'reports' && <Button variant="primary" icon="download" onClick={()=>downloadReport(entity)}>Télécharger</Button>}{entity.type === 'alerts' && entity.status !== 'resolved' && <Button variant="primary" icon="check" onClick={async()=>{const result=await save('alerts',{status:'resolved'},entity.id);if(result){closeModal();notify('L’alerte a été résolue.');}}}>Résoudre l’alerte</Button>}</div></>; }
    else if (modal.kind === 'password') {title='Sécurité du compte';body=<PasswordForm />;}
    else if (modal.kind === 'communication') {title=modal.title || 'Contacter un média';body=<ContactComposer entity={entity} />;}
    else if (modal.kind === 'support') {title='Votre équipe support, 24/7';body=<div className="support-dialog"><div className="support-big-icon"><Icon name="support" size={48} /></div><h3>Nous sommes à vos côtés.</h3><p>Une question sur votre veille, une alerte ou votre compte ? Contactez notre équipe.</p><a className="support-contact" href="mailto:support@ghostroar.com"><Icon name="mail" />support@ghostroar.com<Icon name="arrow" /></a><a className="support-contact" href="tel:+237651395504"><Icon name="phone" />+237 651 395 504<Icon name="arrow" /></a><small>Votre espace est sécurisé. Ne communiquez jamais votre mot de passe.</small></div>;}
    else if (modal.kind === 'plans') {title='Une réputation à la hauteur de vos ambitions';body=<><p className="form-intro">Choisissez l’accompagnement adapté à votre présence numérique.</p><div className="plans-grid">{[['Essentiel','Une veille claire, au quotidien.','Surveillance des sources, suivi des mentions, alertes personnalisées.'],['Professionnel','Anticipez. Analysez. Agissez.','Toutes les sources, rapports avancés, analyse de réputation et équipe dédiée.'],['Entreprise','Votre réputation, sans compromis.','Gestion multi-profils, War Room, stratégie média et accompagnement 24/7.']].map(([name,caption,description])=><div className="plan-card" key={name}><Icon name="shield" size={29} /><h3>{name}</h3><strong>{caption}</strong><p>{description}</p><a href={`mailto:support@ghostroar.com?subject=${encodeURIComponent(`Demande d’information — Offre ${name}`)}`} className="button button-primary">Parlons de votre projet <Icon name="arrow" size={15} /></a></div>)}</div></>;}
    else if (modal.kind === 'recommendations') {title='Sources recommandées pour votre activité';body=<><p className="form-intro">Renforcez votre couverture des sujets technologiques et de l’actualité africaine.</p>{[['Investir au Cameroun','https://www.investiraucameroun.com','Économie et entrepreneuriat au Cameroun.'],['Jeune Afrique','https://www.jeuneafrique.com','Actualité et influence sur le continent africain.'],['TechCabal','https://techcabal.com','Innovation et écosystème technologique africain.']].map(([name,url,description])=><div className="recommendation-row" key={name}><PlatformIcon platform="presse" /><div><strong>{name}</strong><p>{description}</p></div><Button icon="plus" onClick={()=>edit('sources',undefined,{name,url,description,platform:'presse',category:'media',status:'connected'})}>Ajouter</Button></div>)}</>;}
    else if (modal.kind === 'history' && entity) {title=`Historique — ${entity.name}`;body=<><div className="history-entry"><Icon name="user" /><div><strong>Contact ajouté à votre réseau</strong><p>{entity.company} · {entity.role}</p><small>{entity.date ? new Date(entity.date).toLocaleDateString('fr-FR') : '12 septembre 2026'}</small></div></div>{entity.notes ? <div className="history-entry"><Icon name="file" /><div><strong>Notes de relation</strong><p className="preserve-lines">{entity.notes}</p></div></div> : <EmptyState title="Aucune note pour le moment" message="Ajoutez une note après votre prochain échange." icon="file" />}<div className="modal-footer"><Button icon="edit" variant="primary" onClick={()=>edit('contacts',entity)}>Ajouter une note</Button></div></>;}
    else if (modal.kind === 'calendar') {title='Calendrier éditorial';body=<><p className="form-intro">Retrouvez vos publications et planifiez les prochaines prises de parole.</p>{data.publications.filter(p=>p.status !== 'archived').sort((a,b)=>String(a.date).localeCompare(String(b.date))).map(post=><button className="calendar-event" key={post.id} onClick={()=>detail(post)}><span className="event-date">{post.date ? new Date(post.date).toLocaleDateString('fr-FR',{day:'2-digit',month:'short'}) : 'À définir'}</span><PlatformIcon platform={post.platform} /><span>{post.name}</span><Badge status={post.status} subtle /></button>)}<div className="modal-footer"><Button variant="primary" icon="plus" onClick={()=>edit('publications',undefined,{status:'scheduled'})}>Programmer une publication</Button></div></>;}
    else if (modal.kind === 'team') {title='Équipe de crise';body=<div className="team-dialog">{[['Arnaud Kenne','Administrateur'],['Camille Dubois','Responsable Communication'],['Julien Moreau','Analyste Senior'],['Sophie Leroy','Conseiller Juridique'],['Thomas Bernard','Expert Médias'],['Élodie Martin','Community Manager']].map(([name,role],i)=><div className="team-person" key={name}>{i===0?<Avatar />:<span className={`initial-avatar color-${i}`}>{name.split(' ').map(p=>p[0]).join('')}</span>}<span><strong>{name}</strong><small>{role}</small></span><i className={`dot ${i<4?'green':'muted'}`} /><small>{i<4?'En ligne':'Absent'}</small></div>)}<Button variant="primary" icon="send" onClick={()=>openModal({kind:'communication',title:'Communiquer avec l’équipe'})}>Communiquer avec l’équipe</Button></div>;}
  }
  return <>{modal && <Modal title={title} onClose={closeModal} wide={modal.kind === 'plans' || (modal.kind === 'detail' && modal.entity?.type === 'reports')}>{body}</Modal>}{notice && <div className={`toast ${notice.error ? 'toast-error' : ''}`} role={notice.error ? 'alert' : 'status'}><span className="toast-icon"><Icon name={notice.error ? 'alert' : 'success'} size={21} /></span><span>{notice.message}</span><IconButton name="close" label="Fermer la notification" onClick={clearNotice} /></div>}</>;
}
